### PR TITLE
chore: add fixtures to package

### PR DESCRIPTION
**Pull request by brendaHuang**
Package fixtures for @rehearsal/test-support

### CODE REVIEW

**Review by wondersloth — APPROVED** [review]

**Comment by egorio** [comment]
This won't work. The release process will just be stuck trying to pack all fixtures and their node_modules.

**Review by egorio — CHANGES_REQUESTED** [review]
We removed fixtures at some point because packages are not able to be released with them because of the size or node_modules https://github.com/rehearsal-js/rehearsal-js/pull/723/files.

If you want to return fixtures, you need to add a step to release.js to remove them. Here is a solution: https://github.com/rehearsal-js/rehearsal-js/commit/85ecd85e1342b59506d3632a8b4ac8d72bbed448

**Comment by egorio** [comment]
If you want to return fixtures, you need to add a step to release.js to remove:

```
packages/test-support/fixtures/ember/addon-template/node_modules
packages/test-support/fixtures/ember/app-template/node_modules
```

**Comment by wondersloth** [comment]
We possibly can add a prepack hook to the package so that it removes node_modules as well. That may help.

**Comment by egorio** [comment]
@wondersloth we can just clean those folders during release: https://github.com/rehearsal-js/rehearsal-js/commit/85ecd85e1342b59506d3632a8b4ac8d72bbed448, but the question is do we need to install those deps at all?

**Comment by chadhietala** [comment]
@brendaHuang what issue is this associated with?

**Comment by brendaHuang** [comment]
@chadhietala I am trying to import these fixtures to be used for smoke-test.

**Comment by chadhietala** [comment]
based on our sync I'm going to close this PR

**Pull request closed without merging**
