### PR TITLE
test: smoke-test usecase with typedef

### PR DESCRIPTION
**Pull request by lynchbomb**
Ref: https://github.com/rehearsal-js/rehearsal-js/issues/1216

### CODE REVIEW

**Comment by wondersloth** [comment]
@lynchbomb it's understood this PR is in-progress, just wanted to bring it to your attention.

@egorio mentioned that this PR updated snapshots and is dropping files after the newly added typedef test case.

I pulled down the branch and ran the tests, its was passing, but it seems like we need some assertions for CLI output.

I added something like the following:

```
diff --git a/packages/smoke-test/test/commands/fix.test.ts b/packages/smoke-test/test/commands/fix.test.ts
index e3995233..de660956 100644
--- a/packages/smoke-test/test/commands/fix.test.ts
+++ b/packages/smoke-test/test/commands/fix.test.ts
@@ -69,7 +69,9 @@ describe('fix command', () => {
       }
     );
 
-    expect(cleanOutput(result.stdout, project.baseDir)).toMatchSnapshot();
+    const output = cleanOutput(result.stdout, project.baseDir);
+    expect(output).contains('/app/components/jumbo.hbs');
+    expect(output).toMatchSnapshot();
     expectFile(join(projectRoot, 'app/components/map.hbs')).toMatchSnapshot();
     expectFile(join(projectRoot, 'app/components/map.ts')).toMatchSnapshot();
     expectFile(join(projectRoot, 'app/components/share-button.ts')).toMatchSnapshot();
```

This start to show the test failing.

**Comment by egorio** [comment]
@lynchbomb 

There is a problem with @typedef codefix, I think.

Typescript's typedef's codefix doesn't care about where where the @typedef comment is.
In the example, the @typedef is a part of a method's comment.

```
export default class AudienceDemographics extends Component {
  /**
   * List of items to be rendered in the bar chart
   * @typedef {{ count: number }} HeadCount
   * @returns {HeadCount}
   */
  get something() {
    return {
      count: this.args.someNumber,
    };
  }
}
```

If you would run codefix in IDE (you can test it [there](https://www.typescriptlang.org/play?ssl=10&ssc=2&pln=1&pc=1#code/KYDwDg9gTgLgBAE2AMwIYFcA28DGnUDOBcAguggJbAB2OwAIsALYQDmUqYAFhTsQN4AoOHAD0AKnHCR4uABkKBeBGRwKMZsRgQ4AI2BwoNJEYRrqcGFwO7UUODi52Y0uLIACMAJ5hgSVfz8DhDo1DAAXHDU6Ez69gC+8XAAEsCoCADCIWGuHkYw6FDUAqnpWaEw8bmi0qzA8AQQTPU81KwAFACUcEIihvWFFtGYmADc0lXxQA)), it will just brakes file's syntax because it will adds type in the middle of class:

```
export default class AudienceDemographics extends Component {
  type HeadCount = { count: number; };
  get something(): HeadCount {
    return {
      count: this.args.someNumber,
    };
  }
}
```

Seems we need to improve [@typedef codefix] (https://github.com/egorio/TypeScript/blob/main/src/services/codefixes/convertTypedefToType.ts) to add type in the scopes where they are appropriate to be - file root or current namespace root.

**Comment by egorio** [comment]
@lynchbomb FIY: It fails on `service.getDiagnostics(fileName);` in `DiagnosticCommentPlugin` running under `GlintService` on `.ts` file with "greek" symbols (𝚪, χ).

Not sure where those greek symbols came from in this case, but feel this is somehow related to a broken syntax because of comment above.

**Comment by egorio** [comment]
This case is fixed

**Pull request closed without merging**
